export const Permissions = {
  PlatformTenantCreate: "platform:tenant:create",
  TenantRead: "tenant:read",
  TenantUpdate: "tenant:update",
  TenantSettingsUpdate: "tenant-settings:update",
  TenantBrandingUpdate: "tenant-branding:update",
  LandingPageRead: "landing-page:read",
  LandingPageManage: "landing-page:manage",
  ProfessionalRead: "professional:read",
  ProfessionalCreate: "professional:create",
  ProfessionalManage: "professional:manage",
  ServiceRead: "service:read",
  ServiceCreate: "service:create",
  ServiceManage: "service:manage",
  EquipmentRead: "equipment:read",
  EquipmentCreate: "equipment:create",
  EquipmentManage: "equipment:manage",
  PackageRead: "package:read",
  PackageCreate: "package:create",
  PackageManage: "package:manage",
  CustomerRead: "customer:read",
  CustomerCreate: "customer:create",
  CustomerUpdate: "customer:update",
  AppointmentRead: "appointment:read",
  AppointmentCreate: "appointment:create",
  AppointmentReschedule: "appointment:reschedule",
  AppointmentCancel: "appointment:cancel",
  AppointmentCheckIn: "appointment:check-in",
  DepositConfirm: "deposit:confirm",
  SessionStart: "session:start",
  SessionComplete: "session:complete",
  PaymentRead: "payment:read",
  PaymentCreate: "payment:create",
  AuditRead: "audit:read",
  UserManage: "user:manage",
  RoleManage: "role:manage",
} as const;

export type PermissionCode = (typeof Permissions)[keyof typeof Permissions];

export const SystemRoleCodes = {
  PlatformAdmin: "platform_admin",
  TenantAdmin: "tenant_admin",
  Reception: "reception",
  Professional: "professional",
} as const;

export type SystemRoleCode = (typeof SystemRoleCodes)[keyof typeof SystemRoleCodes];

export const DEFAULT_ROLE_PERMISSIONS: Readonly<Record<SystemRoleCode, readonly PermissionCode[]>> = {
  platform_admin: Object.values(Permissions),
  tenant_admin: [
    Permissions.TenantRead,
    Permissions.TenantUpdate,
    Permissions.TenantSettingsUpdate,
    Permissions.TenantBrandingUpdate,
    Permissions.LandingPageRead,
    Permissions.LandingPageManage,
    Permissions.ProfessionalRead,
    Permissions.ProfessionalCreate,
    Permissions.ProfessionalManage,
    Permissions.ServiceRead,
    Permissions.ServiceCreate,
    Permissions.ServiceManage,
    Permissions.EquipmentRead,
    Permissions.EquipmentCreate,
    Permissions.EquipmentManage,
    Permissions.PackageRead,
    Permissions.PackageCreate,
    Permissions.PackageManage,
    Permissions.CustomerRead,
    Permissions.CustomerCreate,
    Permissions.CustomerUpdate,
    Permissions.AppointmentRead,
    Permissions.AppointmentCreate,
    Permissions.AppointmentReschedule,
    Permissions.AppointmentCancel,
    Permissions.AppointmentCheckIn,
    Permissions.DepositConfirm,
    Permissions.SessionStart,
    Permissions.SessionComplete,
    Permissions.PaymentRead,
    Permissions.PaymentCreate,
    Permissions.AuditRead,
    Permissions.UserManage,
    Permissions.RoleManage,
  ],
  reception: [
    Permissions.ProfessionalRead,
    Permissions.ServiceRead,
    Permissions.EquipmentRead,
    Permissions.PackageRead,
    Permissions.PackageCreate,
    Permissions.CustomerRead,
    Permissions.CustomerCreate,
    Permissions.CustomerUpdate,
    Permissions.AppointmentRead,
    Permissions.AppointmentCreate,
    Permissions.AppointmentReschedule,
    Permissions.AppointmentCancel,
    Permissions.AppointmentCheckIn,
    Permissions.DepositConfirm,
    Permissions.PaymentRead,
    Permissions.PaymentCreate,
  ],
  professional: [
    Permissions.CustomerRead,
    Permissions.AppointmentRead,
    Permissions.EquipmentRead,
    Permissions.PackageRead,
    Permissions.SessionStart,
    Permissions.SessionComplete,
  ],
};
